### PR TITLE
Added Final html, css and icon files

### PR DESCRIPTION
**Pull request by karthi07**
Youtube clone website

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
**Pull Request under review by David Elí**

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🛑 👀 🔍 
### Hi Team. 😄 
### Nice job so far but we have some issues to solve before move on. 💯 👍 

- [ ] Remember about descriptive README file - feel free to use this [template](https://github.com/microverseinc/readme-template).

- [ ] Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.

### Let's check the div where the video is, its must contain:

- [ ] It has like and dislike icons ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_like_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)).

- [ ]  It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png)) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

- [ ] It shows the avatar of the user who uploaded the video ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_avatar_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

- [ ] It has a subscribe button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

### Sidebar Recommended videos.

- [ ] It shows the recommended video's thumbnail preview ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_thumbnail_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

- [ ] It shows the title of the video ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_title_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

- [ ] It shows the number of views ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_views_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

### Please style the footer section.

Screen Shot 2020-02-20 at 7 04 30 AM

 **To look like this 😄 :**

Screen Shot 2020-02-20 at 7 14 36 AM

### Store images and CSS files in separate folders.

Screen Shot 2020-02-20 at 7 07 43 AM

Screen Shot 2020-02-20 at 7 08 38 AM

Please make the changes required and submit a new code review once you are ready! 🙏 

Happy coding! 😄 💻 

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @karthi07 and @MrSayyod, nice work making some of the changes requested by the previous reviewer.
However, we left some of the requirements. Find comments below:
- I found markup errors [here](https://validator.w3.org/). Kindly fix them
err
- Also the previous reviewer made mention of making your README looks professional. Kindly check the template given or use [this](https://github.com/microverseinc/readme-template) and edit it.
Good job 😄 

Kindly make these changes and submit code review 👍 
Happy coding 💻 
Daniel Larbi Addo

**Comment by majovanilla** [comment]
# Code Review Request  👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @MrSayyod and @karthi07 , 👋

## Good job on this project! 👍

I like the fact that you link the side videos to the real youtube page =)

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- You still have some errors and warning on your HTML file as pointed out in the previous review. Please address those.

Screenshot from 2020-02-21 02-26-10


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Remove the background color of your header and make it look like the original one. This will improve the general styling of your project. 

Screenshot from 2020-02-21 02-32-56

- Change the notification icon to an icon and not an image (this one has a background) I recommend you use this [website](icons8.com) to get your icons for free.

Screenshot from 2020-02-21 02-32-38

- There is a link tag that is not working properly and appears on your video title.

Screenshot from 2020-02-21 02-33-01

- Increase the font size of the suggested videos. It's too small and it's difficult to read.
Screenshot from 2020-02-21 02-35-02


## Please, make all REQUIRED changes and submit your request again! 😀
## STATUS:  changes required 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by majovanilla** [comment]
Hey @MrSayyod and @karthi07 , 👋

## Good job on this project! 👍

You implemented all requested changes and are ALMOST good to go.

In your HTML validator, you have a warning. Every time you use the section tag you are required to add a heading. If you don't use a heading, you can change the tag to div.

## STATUS:  project approved.

As a tip, the HTML files are usually named index.html or main.html. So you should follow that convention for simple projects like this one.

I also strongly suggest you add the optional requirements, as this is a must if you want to be a TSE in the future. 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Pull request merged**
